numpy/numpy-stubs

numpy/__init__.pyi
setup.py
tests/README.md
tests/test_simple.py

It doesn't appear that the released mypy supports _stub packages right now, so for now we have to add to MYPYPATH manually.
Something else to consider is how to sync versions with numpy, but we can deal with that later, if we start our numbers low enough.
This adds a very small number of stubs just to verify that installation maybe works.
Fixes #2.

Add basic scaffolding for distributing the package

---

numpy-stubs/__init__.pyi

`numpy.ndarray.__new__` previously did not have any type definitions, meaning that code that directly instantiates `np.ndarray` instances would be flagged by mypy as having unexpected arguments.
I think this should fix the issue - at the very least this change removes what I consider to be invalid warnings on my codebase - although I'm unsure about whether the type for the buffer is correct.

Added hint for ndarray.__new__

---

numpy-stubs/__init__.pyi
tests/fail/simple.py
tests/pass/simple.py

I added a couple of commonly used array creation routines (ones and zeros).
One thing that I would imagine is out of scope of this PR and likely out of scope of this project is pythons treatment of `bool` as a subclass of `int`. This means with `_ShapeLike` we can have something like `np.zeros(False)` pass the analysis, while numpy at runtime raises a `TypeError`.

Array Creation Routines: zeros and ones

---

numpy-stubs/__init__.pyi
tests/pass/simple.py

Closes https://github.com/numpy/numpy-stubs/issues/42.
`np.dtype` accepts a wide variety of lists as dtypes, some examples
include:
- `[('R', 'u1'), ('G', np.unicode_, 1)]`
- `[('R', 'u1', (2, 2)), ('G', np.unicode_, 1)]`
Without further hints mypy is going to type those as `List[object]`,
so precise hints will require that users add annotations. In addition,
typing the above is challenging because the inputs have to be a list,
which is invariant, so you can't use `Union`s inside the list to
reduce the number of cases. Work around that by just accepting
`List[Any]`.

MAINT: broaden allowed lists in `_DtypeLike`

---

setup.py

Closes https://github.com/numpy/numpy-stubs/issues/36.
See the mypy docs:
https://mypy.readthedocs.io/en/latest/installed_packages.html#making-pep-561-compatible-packages
for more information.

MAINT: set `zip_safe` to `False` in `setup.py`

---

test-requirements.txt
tests/test_stubs.py

The most significant benefit is changes to `@overload` around what
counts as overlapping signatures that could unlock some functionality;
see e.g.
- https://github.com/numpy/numpy-stubs/pull/44#discussion_r396186738
- https://github.com/numpy/numpy-stubs/pull/11#issuecomment-369444243

MAINT: upgrade mypy to 0.770 (the latest)

---

numpy-stubs/__init__.pyi
tests/reveal/constants.py

Scraped them with this script:
```python
import numpy as np
def main():
constants = []
for obj_name in dir(np):
obj = getattr(np, obj_name)
if isinstance(obj, float):
constants.append(f'{obj_name}: float')
print('\n'.join(sorted(constants)))
if __name__ == '__main__':
main()
```

ENH: add numerical constants

---

numpy-stubs/__init__.pyi
tests/pass/ufuncs.py

Follow up to https://github.com/numpy/numpy-stubs/pull/44.
SciPy actually uses `__name__`, so add it.

ENH: add __name__ attribue to ufuncs

---

.travis.yml
test-requirements.txt

This also required bumping the flake8 version.
While experimenting with plugins in https://github.com/numpy/numpy-stubs/pull/56 I was getting CI failures on 3.7 but not 3.6, so it seemed prudent to expand our CI matrix.

Add Python 3.8 to the CI matrix

---

numpy-stubs/__init__.pyi

We have a
```
def __getattr__(name: str) -> Any: ...
```
since not everything is typed yet. It was originally at the bottom of
the `__init__.pyi` file, but has since ended up not at the end because
it's hard to remember to put your code above it. Since it makes sense
to have it somewhere more noticeable than the middle of the file, put
it at the top instead.

MAINT: move __getattr__ to the top of __init__.pyi

---

setup.py

* Added [``typing_extensions``](https://pypi.org/project/typing-extensions/) as a dependency for Python < 3.8.
* Ran black on setup.py.

Added typing_extensions as a dependency for Python < 3.8

---

.travis.yml
runtests.py
scripts/find_ufuncs.py
tests/fail/scalars.py
tests/fail/ufuncs.py
tests/fail/warnings_and_errors.py
tests/pass/scalars.py
tests/pass/simple.py
tests/pass/ufuncs.py
tests/pass/warnings_and_errors.py
tests/reveal/ndarray_conversion.py
tests/reveal/scalars.py
tests/test_stubs.py

In https://github.com/numpy/numpy-stubs/pull/63 black was run on `setup.py`. Follow up by running black on all files in CI. Do an inital pass over the entire codebase so that the CI check will pass.
I'm usually opposed to things like this, but it seems like we're in an early enough stage that it should be ok.

MAINT: run black on all files in CI

---

runtests.py

Now you can run something like
```
./runtests.py --find-missing numpy
```
to get a list of everything that still needs annotations added.

ENH: add runtests option to find untyped module attributes

---

tests/test_stubs.py

Since NumPy officially doesn't support Python 2 anymore, there doesn't
seem to be any particular need to test for it. Note that this doesn't
actually do anything to make the stubs not Python 2 friendly as `.pyi`
syntax has always been 2/3 compatible.

TST: don't run tests in py2 mode

---

.gitignore
numpy-stubs/__init__.pyi
tests/fail/fromnumeric.py
tests/pass/fromnumeric.py
tests/reveal/fromnumeric.py

Continuation of https://github.com/numpy/numpy-stubs/pull/59.
Introduced type hints for the first 11 (public) functions from the [``np.core.fromnumeric``](https://github.com/numpy/numpy/blob/master/numpy/core/fromnumeric.py) module.
Functions
----------
* ``take``
* ``reshape``
* ``choose``
* ``repeat``
* ``put``
* ``swapaxes``
* ``transpose``
* ``partition``
* ``argpartition``
* ``sort``
* ``argsort``

ENH: Add type annotations for the np.core.fromnumeric module: part 1/4

---

tests/README.md

- Remove note about py2 tests versus py3 tests
- Recommend using `runtests.py`

DOC: update testing README

---

setup.py
tests/pass/ndarray_conversion.py
tests/pass/ndarray_shape_manipulation.py
tests/pass/scalars.py
tests/pass/simple.py
tests/test_stubs.py

It seems fair that the code in pass should also run; i.e. that
directory shouldn't contain mypy false positives. Add a test that runs
the modules in that directory and fix the resulting runtime errors.

TST: also run the code in "pass"

---

numpy-stubs/__init__.pyi
numpy-stubs/typing.pyi
tests/fail/array_like.py
tests/pass/array_like.py
tests/reveal/fromnumeric.py

Closes https://github.com/numpy/numpy-stubs/issues/37.
Add tests to check various examples.

ENH: get more specific about _ArrayLike, make it public

---

numpy-stubs/__init__.pyi

I think `_DtypeLike` is better than `Optional[dtype]`. Can you replace them?

Use _DtypeLike instead of Optional[dtype]

---

numpy-stubs/__init__.pyi
tests/fail/fromnumeric.py
tests/pass/fromnumeric.py
tests/reveal/fromnumeric.py

Add annotations for the second batch of ``np.core.fromnumeric`` functions from https://github.com/numpy/numpy-stubs/pull/59/
New Functions
---------------
* ``argmax()``
* ``argmin()``
* ``searchsorted()``
* ``resize()``
* ``squeeze()``
* ``diagonal()``
* ``trace()``
* ``ravel()``
* ``nonzero()``
* ``shape()``
* ``compress()``

ENH: Add type annotations for the np.core.fromnumeric module: part 2/4

---

README.md

Update the README to reflect the upcoming migration of the stubs
into the main NumPy repo. Hopefully this will help clarify the
plan for people interested in contributing.

DOC: Update README to mention pending migration to NumPy

---

runtests.py

Found a few more functions that we shouldn't add types for.

MAINT: add more functions to the blacklist
